name: 'Hello World'
description: 'Greet someone and record the time'

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  hello:
    runs-on: ubuntu:latest
    steps:
      - name: hello-world
        run: echo "Hello World"
